# Copyright (c) 2021 SIGHUP s.r.l All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

---
#########################
#########################
## Golang Linter rules ##
#########################
#########################

# options for analysis running
run:
  # include test files or not, default is true
  tests: false
  # timeout for analysis, e.g. 30s, 5m, default is 1m
  timeout: 10m

# configure golangci-lint
# see https://github.com/golangci/golangci-lint/blob/master/.golangci.example.yml
issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - dupl
        - goconst
    - path: cmd/
      linters:
        - gochecknoinits
        - lll
    - path: cmd/fip-job-status-api/main.go
      linters:
        - gochecknoglobals
linters:
  disable-all: true
  enable:
    - ineffassign
    - asciicheck
    - dogsled
    - dupl
    - funlen
    - gci
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - goconst
    - gocyclo
    - godot
    - godox
    - gofmt
    - goheader
    - goimports
    - gomnd
    - gomodguard
    - goprintffuncname
    - lll
    - misspell
    - nakedret
    - nestif
    - nlreturn
    - nolintlint
    - prealloc
    - scopelint
    - testpackage
    - whitespace
    - wsl

linters-settings:
  gocyclo:
    # minimal code complexity to report, 30 by default
    min-complexity: 15
